### Capstone project 2

### Part 1 loading data

In [33]:
import csv

players = []
try:
    with open('C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject2\\players.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            players.append(row)
except FileNotFoundError:
    print('Error: players.csv not found.')

In [34]:
players

[{'player_id': '101',
  'player_name': 'Virat Kohli',
  'team': 'RCB',
  'matches': '14',
  'runs': '741',
  'fours': '62',
  'sixes': '38'},
 {'player_id': '102',
  'player_name': 'Rohit Sharma',
  'team': 'MI',
  'matches': '14',
  'runs': '560',
  'fours': '48',
  'sixes': '25'},
 {'player_id': '103',
  'player_name': 'Shubman Gill',
  'team': 'GT',
  'matches': '14',
  'runs': '620',
  'fours': '55',
  'sixes': '28'},
 {'player_id': '104',
  'player_name': 'KL Rahul',
  'team': 'LSG',
  'matches': '14',
  'runs': '590',
  'fours': '50',
  'sixes': '22'},
 {'player_id': '105',
  'player_name': 'Ruturaj Gaikwad',
  'team': 'CSK',
  'matches': '14',
  'runs': '610',
  'fours': '58',
  'sixes': '24'},
 {'player_id': '106',
  'player_name': 'Hardik Pandya',
  'team': 'MI',
  'matches': '14',
  'runs': '430',
  'fours': '30',
  'sixes': '20'},
 {'player_id': '107',
  'player_name': 'MS Dhoni',
  'team': 'CSK',
  'matches': '14',
  'runs': '280',
  'fours': '18',
  'sixes': '16'},
 {'player_id': '108',
  'player_name': 'Faf du Plessis',
  'team': 'RCB',
  'matches': '14',
  'runs': '670',
  'fours': '60',
  'sixes': '32'},
 {'player_id': '109',
  'player_name': 'Sanju Samson',
  'team': 'RR',
  'matches': '14',
  'runs': '550',
  'fours': '45',
  'sixes': '25'},
 {'player_id': '110',
  'player_name': 'Yashasvi Jaiswal',
  'team': 'RR',
  'matches': '14',
  'runs': '625',
  'fours': '57',
  'sixes': '30'},
 {'player_id': '111',
  'player_name': 'Rinku Singh',
  'team': 'KKR',
  'matches': '14',
  'runs': '480',
  'fours': '35',
  'sixes': '29'},
 {'player_id': '112',
  'player_name': 'Andre Russell',
  'team': 'KKR',
  'matches': '14',
  'runs': '450',
  'fours': '28',
  'sixes': '35'}]

In [35]:
for p in players:
    print(p)

{'player_id': '101', 'player_name': 'Virat Kohli', 'team': 'RCB', 'matches': '14', 'runs': '741', 'fours': '62', 'sixes': '38'}
{'player_id': '102', 'player_name': 'Rohit Sharma', 'team': 'MI', 'matches': '14', 'runs': '560', 'fours': '48', 'sixes': '25'}
{'player_id': '103', 'player_name': 'Shubman Gill', 'team': 'GT', 'matches': '14', 'runs': '620', 'fours': '55', 'sixes': '28'}
{'player_id': '104', 'player_name': 'KL Rahul', 'team': 'LSG', 'matches': '14', 'runs': '590', 'fours': '50', 'sixes': '22'}
{'player_id': '105', 'player_name': 'Ruturaj Gaikwad', 'team': 'CSK', 'matches': '14', 'runs': '610', 'fours': '58', 'sixes': '24'}
{'player_id': '106', 'player_name': 'Hardik Pandya', 'team': 'MI', 'matches': '14', 'runs': '430', 'fours': '30', 'sixes': '20'}
{'player_id': '107', 'player_name': 'MS Dhoni', 'team': 'CSK', 'matches': '14', 'runs': '280', 'fours': '18', 'sixes': '16'}
{'player_id': '108', 'player_name': 'Faf du Plessis', 'team': 'RCB', 'matches': '14', 'runs': '670', 'fours': '60', 'sixes': '32'}
{'player_id': '109', 'player_name': 'Sanju Samson', 'team': 'RR', 'matches': '14', 'runs': '550', 'fours': '45', 'sixes': '25'}
{'player_id': '110', 'player_name': 'Yashasvi Jaiswal', 'team': 'RR', 'matches': '14', 'runs': '625', 'fours': '57', 'sixes': '30'}
{'player_id': '111', 'player_name': 'Rinku Singh', 'team': 'KKR', 'matches': '14', 'runs': '480', 'fours': '35', 'sixes': '29'}
{'player_id': '112', 'player_name': 'Andre Russell', 'team': 'KKR', 'matches': '14', 'runs': '450', 'fours': '28', 'sixes': '35'}

In [36]:
# Task 3 
print({len(players)})

{12}

### Part 2 – Player Analytics

In [37]:
top_scorer = max(players, key=lambda p: int(p['runs']))
print(top_scorer)

{'player_id': '101', 'player_name': 'Virat Kohli', 'team': 'RCB', 'matches': '14', 'runs': '741', 'fours': '62', 'sixes': '38'}

In [38]:
low_scorer = min(players, key=lambda p: int(p['runs']))
print(low_scorer)

{'player_id': '107', 'player_name': 'MS Dhoni', 'team': 'CSK', 'matches': '14', 'runs': '280', 'fours': '18', 'sixes': '16'}

In [39]:
total_runs = sum(int(p['runs']) for p in players)
avg_runs = total_runs / len(players)
print(round(avg_runs,2))

550.5

In [40]:
print("players with runs > 600")
for p in players:
    if int(p['runs']) > 600:
        print(p)

players with runs > 600
{'player_id': '101', 'player_name': 'Virat Kohli', 'team': 'RCB', 'matches': '14', 'runs': '741', 'fours': '62', 'sixes': '38'}
{'player_id': '103', 'player_name': 'Shubman Gill', 'team': 'GT', 'matches': '14', 'runs': '620', 'fours': '55', 'sixes': '28'}
{'player_id': '105', 'player_name': 'Ruturaj Gaikwad', 'team': 'CSK', 'matches': '14', 'runs': '610', 'fours': '58', 'sixes': '24'}
{'player_id': '108', 'player_name': 'Faf du Plessis', 'team': 'RCB', 'matches': '14', 'runs': '670', 'fours': '60', 'sixes': '32'}
{'player_id': '110', 'player_name': 'Yashasvi Jaiswal', 'team': 'RR', 'matches': '14', 'runs': '625', 'fours': '57', 'sixes': '30'}

In [41]:
print("players with runs < 500")
for p in players:
    if int(p['runs'])<500:
        print(p)

players with runs < 500
{'player_id': '106', 'player_name': 'Hardik Pandya', 'team': 'MI', 'matches': '14', 'runs': '430', 'fours': '30', 'sixes': '20'}
{'player_id': '107', 'player_name': 'MS Dhoni', 'team': 'CSK', 'matches': '14', 'runs': '280', 'fours': '18', 'sixes': '16'}
{'player_id': '111', 'player_name': 'Rinku Singh', 'team': 'KKR', 'matches': '14', 'runs': '480', 'fours': '35', 'sixes': '29'}
{'player_id': '112', 'player_name': 'Andre Russell', 'team': 'KKR', 'matches': '14', 'runs': '450', 'fours': '28', 'sixes': '35'}

### Part 3 Team Analytics

In [42]:
team_player_count = {}
for p in players:
    team_player_count[p['team']] = team_player_count.get(p['team'], 0) + 1

print("players by team:")
for team, count in team_player_count.items():
    print(f"{team} : {count} ")

players by team:
RCB : 2
MI : 2
GT : 1
LSG : 1
CSK : 2
RR : 2
KKR : 2

In [43]:
team_runs = {}
for p in players:
    team_runs[p['team']] = team_runs.get(p['team'], 0) + int(p['runs'])

print("total runs by team:")
for team, runs in team_runs.items():
    print(f"{team}: {runs} ")

total runs by team:
RCB: 1411
MI: 990
GT: 620
LSG: 590
CSK: 890
RR: 1175
KKR: 930

In [44]:
best_team = max(team_runs, key=team_runs.get)
print(f"{best_team} : {team_runs[best_team]} ")

RCB : 1411

In [45]:
worst_team = min(team_runs, key=team_runs.get)
print(f" {worst_team} : {team_runs[worst_team]} ")

 LSG : 590

### Part 4 Boundary Analysis

In [46]:
most_fours = max(players, key=lambda p: int(p['fours']))
print(most_fours)

{'player_id': '101', 'player_name': 'Virat Kohli', 'team': 'RCB', 'matches': '14', 'runs': '741', 'fours': '62', 'sixes': '38'}

In [47]:
most_sixes = max(players, key=lambda p: int(p['sixes']))
print(most_sixes)

{'player_id': '101', 'player_name': 'Virat Kohli', 'team': 'RCB', 'matches': '14', 'runs': '741', 'fours': '62', 'sixes': '38'}

In [48]:
total_fours = sum(int(p['fours']) for p in players)
print( total_fours)

546

In [49]:
total_sixes = sum(int(p['sixes']) for p in players)
print( {total_sixes})

{324}

### Part 5  list set and dictionaries

In [50]:
player_names_list = sorted([p['player_name'] for p in players])
print(player_names_list)

['Andre Russell', 'Faf du Plessis', 'Hardik Pandya', 'KL Rahul', 'MS Dhoni', 'Rinku Singh', 'Rohit Sharma', 'Ruturaj Gaikwad', 'Sanju Samson', 'Shubman Gill', 'Virat Kohli', 'Yashasvi Jaiswal']

In [51]:
teams_set = set(p['team'] for p in players)
print(teams_set)

{'MI', 'CSK', 'RR', 'GT', 'RCB', 'LSG', 'KKR'}

In [52]:
team_runs_dict = {}
for p in players:
    team_runs_dict[p['team']] = team_runs_dict.get(p['team'], 0) + int(p['runs'])
for team, runs in team_runs_dict.items():
    print(f"{team} : {runs}")

RCB : 1411
MI : 990
GT : 620
LSG : 590
CSK : 890
RR : 1175
KKR : 930

In [53]:

player_runs_dict = {p['player_name']: int(p['runs']) for p in players}
for name, runs in player_runs_dict.items():
    print(f"{name}: {runs}")

Virat Kohli: 741
Rohit Sharma: 560
Shubman Gill: 620
KL Rahul: 590
Ruturaj Gaikwad: 610
Hardik Pandya: 430
MS Dhoni: 280
Faf du Plessis: 670
Sanju Samson: 550
Yashasvi Jaiswal: 625
Rinku Singh: 480
Andre Russell: 450

### Part 6  Functions

In [54]:
def find_top_scorer(players):
    top = max(players, key=lambda p: int(p['runs']))
    return top['player_name'], int(top['runs'])

name, runs = find_top_scorer(players)
print(name, runs)

Virat Kohli 741

In [55]:
def calculate_average_runs(players):
    return sum(int(p['runs']) for p in players) / len(players)

print(calculate_average_runs(players))

550.5

In [56]:
def find_best_team(players):
    team_runs = {}
    for p in players:
        team_runs[p['team']] = team_runs.get(p['team'], 0) + int(p['runs'])
    best = max(team_runs, key=team_runs.get)
    return best, team_runs[best]

team, runs = find_best_team(players)
print(f"{team} : {runs} ")

RCB : 1411

In [57]:
def find_total_boundaries(players):
    total_fours = sum(int(p['fours']) for p in players)
    total_sixes = sum(int(p['sixes']) for p in players)
    return total_fours, total_sixes

fours, sixes = find_total_boundaries(players)
print(f"total fours: {fours}")
print(f"total sixes: {sixes}")
print(f"total boundaries: {fours + sixes}")

total fours: 546
total sixes: 324
total boundaries: 870

### Part 7  exception handling

In [58]:
def load_players(filename):
    players = []
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                players.append(row)
        print("file loaded")
    except FileNotFoundError:
        print("error")
    return players

In [59]:
def safe_get_runs(player):
    try:
        runs = int(player['runs'])
        if runs < 0:
            raise ValueError("runs cannot be negative")
        return runs
    except ValueError as e:
        print(e)
        return 0

In [60]:
def safe_get_matches(player):
    try:
        matches = int(player['matches'])
        if matches <= 0:
            raise ValueError("match count cannot be negative")
        return matches
    except ValueError as e:
        print(e)
        return 0

### Part 8 numpy

In [61]:
import numpy as np

runs_array = np.array([int(p['runs']) for p in players])

print()
print(f"total runs: {np.sum(runs_array)}")
print(f"average runs: {np.mean(runs_array):.2f}")
print(f"maximum runs: {np.max(runs_array)}")
print(f"minimum runs: {np.min(runs_array)}")
print(f"standard deviation: {np.std(runs_array):.2f}")
print(f"median runs: {np.median(runs_array)}")

total runs: 6606
average runs: 550.50
maximum runs: 741
minimum runs: 280
standard deviation: 118.64
median runs: 575.0

### Part 9 Pandas

In [62]:
import pandas as pd

df = pd.read_csv('C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject2\\players.csv')
df

    player_id       player_name team  matches  runs  fours  sixes
0         101       Virat Kohli  RCB       14   741     62     38
1         102      Rohit Sharma   MI       14   560     48     25
2         103      Shubman Gill   GT       14   620     55     28
3         104          KL Rahul  LSG       14   590     50     22
4         105   Ruturaj Gaikwad  CSK       14   610     58     24
5         106     Hardik Pandya   MI       14   430     30     20
6         107          MS Dhoni  CSK       14   280     18     16
7         108    Faf du Plessis  RCB       14   670     60     32
8         109      Sanju Samson   RR       14   550     45     25
9         110  Yashasvi Jaiswal   RR       14   625     57     30
10        111       Rinku Singh  KKR       14   480     35     29
11        112     Andre Russell  KKR       14   450     28     35

In [63]:
print("top 5 run scorers")
df.sort_values('runs', ascending=False).head(5)[['player_name','team','matches','runs']]

top 5 run scorers

        player_name team  matches  runs
0       Virat Kohli  RCB       14   741
7    Faf du Plessis  RCB       14   670
9  Yashasvi Jaiswal   RR       14   625
2      Shubman Gill   GT       14   620
4   Ruturaj Gaikwad  CSK       14   610

In [64]:
print("players sorted by runs:")
df.sort_values('runs', ascending=False)[['player_name','team','runs']].reset_index(drop=True)

players sorted by runs:

         player_name team  runs
0        Virat Kohli  RCB   741
1     Faf du Plessis  RCB   670
2   Yashasvi Jaiswal   RR   625
3       Shubman Gill   GT   620
4    Ruturaj Gaikwad  CSK   610
5           KL Rahul  LSG   590
6       Rohit Sharma   MI   560
7       Sanju Samson   RR   550
8        Rinku Singh  KKR   480
9      Andre Russell  KKR   450
10     Hardik Pandya   MI   430
11          MS Dhoni  CSK   280

In [65]:
print("team-wise runs:")
team_total = df.groupby('team')['runs'].sum().sort_values(ascending=False).reset_index()
team_total

team-wise runs:

  team  runs
0  RCB  1411
1   RR  1175
2   MI   990
3  KKR   930
4  CSK   890
5   GT   620
6  LSG   590

In [66]:
print("team wise avg runs:")
team_avg = df.groupby('team')['runs'].mean().sort_values(ascending=False).reset_index()
team_avg.columns = ['Team', 'Average Runs']
team_avg['Average Runs'] = team_avg['Average Runs'].round(2)
team_avg

team wise avg runs:

  Team  Average Runs
0  RCB         705.5
1   GT         620.0
2  LSG         590.0
3   RR         587.5
4   MI         495.0
5  KKR         465.0
6  CSK         445.0

In [67]:
print("players with runs > 600:")
df[df['runs'] > 600][['player_name','team','runs']].reset_index(drop=True)

players with runs > 600:

        player_name team  runs
0       Virat Kohli  RCB   741
1      Shubman Gill   GT   620
2   Ruturaj Gaikwad  CSK   610
3    Faf du Plessis  RCB   670
4  Yashasvi Jaiswal   RR   625

In [68]:
top_team_row = df.groupby('team')['runs'].sum().idxmax()
top_team_runs = df.groupby('team')['runs'].sum().max()
print(f" {top_team_row} : {top_team_runs} ")

 RCB : 1411

### Report

In [69]:
top_name, top_runs = find_top_scorer(players)
low_name = low_scorer['player_name']
low_runs = int(low_scorer['runs'])
best_team_name, best_team_runs = find_best_team(players)
tf, ts = find_total_boundaries(players)

top5 = sorted(players, key=lambda p: int(p['runs']), reverse=True)[:5]

report_lines = f''' 
    total players: {len(players)}
    Total Runs: {sum(int(p['runs']) for p in players)}
    Average Runs: {calculate_average_runs(players):.2f}
    Highest Scorer: {top_name} {top_runs}
    Lowest Scorer: {low_name} {low_runs} 
    team-wise runs:
    {team_total}
    top5:
    {top5}
    most fours: {most_fours}
    most sixes: {most_sixes}

'''

with open('cricket_report.txt', 'w') as f:
    f.write((report_lines))
print("report generated")

report generated

### bonus tasks

In [70]:
top_players_df = df[df['runs'] > 600]
top_players_df.to_csv('top_players.csv', index=False)
top_players_df

   player_id       player_name team  matches  runs  fours  sixes
0        101       Virat Kohli  RCB       14   741     62     38
2        103      Shubman Gill   GT       14   620     55     28
4        105   Ruturaj Gaikwad  CSK       14   610     58     24
7        108    Faf du Plessis  RCB       14   670     60     32
9        110  Yashasvi Jaiswal   RR       14   625     57     30

In [71]:
team_summary = df.groupby('team').agg(
    Total_Runs=('runs', 'sum'),
    Average_Runs=('runs', 'mean'),
    Player_Count=('player_id', 'count')
).reset_index()
team_summary['Average_Runs'] = team_summary['Average_Runs'].round(2)
team_summary.columns = ['Team', 'Total Runs', 'Average Runs', 'Player Count']
team_summary = team_summary.sort_values('Total Runs', ascending=False).reset_index(drop=True)
team_summary.to_csv('team_summary.csv', index=False)
team_summary

  Team  Total Runs  Average Runs  Player Count
0  RCB        1411         705.5             2
1   RR        1175         587.5             2
2   MI         990         495.0             2
3  KKR         930         465.0             2
4  CSK         890         445.0             2
5   GT         620         620.0             1
6  LSG         590         590.0             1

In [72]:
def main():
    while True:
        print('1.Player Analysis')
        print('2.Team Analysis')
        print('3.Boundary Analysis')
        print('4.Export Reports')
        print('5.Exit')

        choice = input('Enter your choice: ')

        if choice == '1':
            top_scorer = max(players, key=lambda p: int(p['runs']))
            print(top_scorer)
            low_scorer = min(players, key=lambda p: int(p['runs']))
            total_runs = sum(int(p['runs']) for p in players)
            avg_runs = total_runs / len(players)
            print(round(avg_runs,2))
            print("players with runs > 600")
            for p in players:
                if int(p['runs']) > 600:
                    print(p)
            print("players with runs < 500")
            for p in players:
                if int(p['runs'])<500:
                    print(p)
        elif choice == '2':
            team_player_count = {}
            for p in players:
                team_player_count[p['team']] = team_player_count.get(p['team'], 0) + 1

            print("players by team:")
            for team, count in team_player_count.items():
                print(f"{team} : {count} ")
            team_runs = {}
            for p in players:
                team_runs[p['team']] = team_runs.get(p['team'], 0) + int(p['runs'])

            print("total runs by team:")
            for team, runs in team_runs.items():
                print(f"{team}: {runs} ")
            best_team = max(team_runs, key=team_runs.get)
            print(f"{best_team} : {team_runs[best_team]} ")
            worst_team = min(team_runs, key=team_runs.get)
            print(f" {worst_team} : {team_runs[worst_team]} ")

        elif choice == '3':
            most_fours = max(players, key=lambda p: int(p['fours']))
            print(most_fours)
            most_sixes = max(players, key=lambda p: int(p['sixes']))
            print(most_sixes)
            total_fours = sum(int(p['fours']) for p in players)
            print( total_fours)
            total_sixes = sum(int(p['sixes']) for p in players)
            print( {total_sixes})
        elif choice == '4':
            player_names_list = sorted([p['player_name'] for p in players])
            print(player_names_list)
            teams_set = set(p['team'] for p in players)
            print(teams_set)
            team_runs_dict = {}
            for p in players:
                team_runs_dict[p['team']] = team_runs_dict.get(p['team'], 0) + int(p['runs'])
            for team, runs in team_runs_dict.items():
                print(f"{team} : {runs}")

            player_runs_dict = {p['player_name']: int(p['runs']) for p in players}
            for name, runs in player_runs_dict.items():
                print(f"{name}: {runs}")
        elif choice == '5':
            print('Exiting!')
            break
        else:
            print('Invalid choice.')
            break

In [73]:
main()

1.Player Analysis
2.Team Analysis
3.Boundary Analysis
4.Export Reports
5.Exit
Exiting!