### Python Capstone Project 1

### Part 1 - File Handling

In [ ]:
#Task1 - read the csv file 
import csv
orders = []
try:
    with open('C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject1\\orders.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            orders.append(row)
except FileNotFoundError:
    print("make sure the file path is correct and the file exists")

In [8]:
#Task2- Display all the orders
for order in orders:
    print(order)

{'order_id': '1001', 'customer_name': 'Rahul Sharma', 'city': 'Hyderabad', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '65000'}
{'order_id': '1002', 'customer_name': 'Priya Reddy', 'city': 'Bangalore', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '2', 'price': '25000'}
{'order_id': '1003', 'customer_name': 'Amit Kumar', 'city': 'Mumbai', 'product': 'Chair', 'category': 'Furniture', 'quantity': '3', 'price': '5000'}
{'order_id': '1004', 'customer_name': 'Sneha Patel', 'city': 'Chennai', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '70000'}
{'order_id': '1005', 'customer_name': 'Farhan Ali', 'city': 'Delhi', 'product': 'Table', 'category': 'Furniture', 'quantity': '2', 'price': '12000'}
{'order_id': '1006', 'customer_name': 'Neha Singh', 'city': 'Hyderabad', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '1', 'price': '28000'}
{'order_id': '1007', 'customer_name': 'Arjun Verma', 'city': 'Pune', 'product': 'Chair', 'category': 'Furniture', 'quantity': '4', 'price': '5500'}
{'order_id': '1008', 'customer_name': 'Meera Nair', 'city': 'Bangalore', 'product': 'TV', 'category': 'Electronics', 'quantity': '1', 'price': '45000'}
{'order_id': '1009', 'customer_name': 'Kiran Rao', 'city': 'Hyderabad', 'product': 'Table', 'category': 'Furniture', 'quantity': '1', 'price': '13000'}
{'order_id': '1010', 'customer_name': 'Ravi Kumar', 'city': 'Mumbai', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '2', 'price': '27000'}
{'order_id': '1011', 'customer_name': 'Deepak Jain', 'city': 'Delhi', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '68000'}
{'order_id': '1012', 'customer_name': 'Ananya Gupta', 'city': 'Hyderabad', 'product': 'TV', 'category': 'Electronics', 'quantity': '2', 'price': '47000'}

In [9]:
#Task3 - Total Orders 
print(len(orders))

12

### Part 2 - Revenue Analysis

In [21]:
#Task4 - Total Revenue
total_revenue = 0
for order in orders:
    total_revenue += int(order['quantity']) * int(order['price'])
print(total_revenue)

548000

In [26]:
#Task5 Highest Value Order
highest_value_order = 0 
order_id = 0
for order in orders:
    highest_value_order = max(highest_value_order, int(order['quantity']) * int(order['price']))
print(highest_value_order)

94000

In [27]:
#Task6 Lowest Value Order
lowest_value_order = float('inf')
order_id = 0
for order in orders:
    lowest_value_order = min(lowest_value_order, int(order['quantity']) * int(order['price']))
print(lowest_value_order)

13000

In [29]:
#Task7 Avg Value Order
total_value = 0
for order in orders:
    total_value += int(order['quantity']) * int(order['price'])
avg_value_order = total_value / len(orders)
print(round(avg_value_order, 2))

45666.67

### Part 3 - Customer Analysis

In [35]:
#Task8 Unique Customers
unique_cust = set()
for order in orders:
    unique_cust.add(order['customer_name'])
print(*unique_cust, sep="\n")

Ananya Gupta
Amit Kumar
Priya Reddy
Meera Nair
Kiran Rao
Neha Singh
Farhan Ali
Arjun Verma
Deepak Jain
Sneha Patel
Ravi Kumar
Rahul Sharma

In [37]:
#Task9 number of  unique customers
len(unique_cust)

12

In [39]:
#Task10 customer with highest value order
for order in orders:
    if int(order['quantity']) * int(order['price']) == highest_value_order:
        print(order)

{'order_id': '1012', 'customer_name': 'Ananya Gupta', 'city': 'Hyderabad', 'product': 'TV', 'category': 'Electronics', 'quantity': '2', 'price': '47000'}

### Part 4 - Product Analysis

In [42]:
#task11 order of products
order_of_products = {}
for order in orders:
    product = order['product']
    order_of_products[product] = order_of_products.get(product, 0) + 1
order_of_products

{'Laptop': 3, 'Mobile': 3, 'Chair': 2, 'Table': 2, 'TV': 2}

In [43]:
#task12 revenue of products
revenue_of_products = {}
for order in orders:
    product = order['product']
    price = int(order['price'])
    quantity = int(order['quantity'])
    revenue_of_products[product] = revenue_of_products.get(product, 0) + (price * quantity)
revenue_of_products

{'Laptop': 203000,
 'Mobile': 132000,
 'Chair': 37000,
 'Table': 37000,
 'TV': 139000}

In [136]:
#task13 most sold 
max_sold_value = max(order_of_products.values())
max_sold_product = [key for key, val in order_of_products.items() if val == max_sold_value]
print(*max_sold_product, sep='\n')

Laptop
Mobile

In [137]:
#task14 least sold 
min_sold_value = min(order_of_products.values())
min_sold_products = [key for key, val in order_of_products.items() if val == min_sold_value]
print(*min_sold_products, sep='\n')

Chair
Table
TV

In [56]:
#task 15 revenue by category 
revenue_by_category = {}
for order in orders:
    category = order['category']
    revenue_by_category[category] = revenue_by_category.get(category, 0) + (int(order['quantity']) * int(order['price']))
print(revenue_by_category)

{'Electronics': 474000, 'Furniture': 74000}

### Part 5 - City Analysis

In [57]:
#task16 orders by city
orders_by_city = {}
for order in orders:
    city = order['city']
    orders_by_city[city] = orders_by_city.get(city, 0) + 1
print(orders_by_city)

{'Hyderabad': 4, 'Bangalore': 2, 'Mumbai': 2, 'Chennai': 1, 'Delhi': 2, 'Pune': 1}

In [58]:
#task17 revenue by city
revenue_by_city = {}
for order in orders:
    city = order['city']
    revenue_by_city[city] = revenue_by_city.get(city, 0) + (int(order['quantity']) * int(order['price']))  
print(revenue_by_city)

{'Hyderabad': 200000, 'Bangalore': 95000, 'Mumbai': 69000, 'Chennai': 70000, 'Delhi': 92000, 'Pune': 22000}

In [ ]:
#task 18 city with highest revenue 
max_revenue_city_value = max(revenue_by_city.values()) 
max_revenue_city = [k for k,v in revenue_by_city.items() if v == max_revenue_city]
print(*max_revenue_city, sep='\n')

Hyderabad

### Part 6 - List, Set, Dictionaries

In [69]:
#task19 
product_names = [] 
for order in orders:
    product_names.append(order['product'])
product_names = sorted(set(product_names))
print(*product_names, sep='\n')

Chair
Laptop
Mobile
TV
Table

In [72]:
#task 20 all cities
cities = set()
for order in orders:
    cities.add(order['city'])
print(*cities, sep='\n')

Delhi
Chennai
Pune
Mumbai
Hyderabad
Bangalore

In [73]:
#task 21 revenue by city
revenue_by_city = {}
for order in orders:
    city = order['city']
    revenue_by_city[city] = revenue_by_city.get(city, 0) + (int(order['quantity']) * int(order['price']))  
print(revenue_by_city)

{'Hyderabad': 200000, 'Bangalore': 95000, 'Mumbai': 69000, 'Chennai': 70000, 'Delhi': 92000, 'Pune': 22000}

In [74]:
#task 22 quantity of each product sold 
quantity_by_product = {}
for order in orders:
    product = order['product']
    quantity_by_product[product] = quantity_by_product.get(product, 0) + int(order['quantity'])
print(quantity_by_product)

{'Laptop': 3, 'Mobile': 5, 'Chair': 7, 'Table': 3, 'TV': 3}

### Part 7 - Functions

In [ ]:
#task 23
def calculate_total_revenue():
    total_revenue = 0
    for order in orders:
        total_revenue += int(order['quantity']) * int(order['price'])
    print(total_revenue)

In [82]:
calculate_total_revenue()

548000

In [124]:
#task 24
def find_top_product():
    product_revenue = {}
    for order in orders:
        product = order['product']
        revenue = int(order['quantity']) * int(order['price'])
        product_revenue[product] = product_revenue.get(product, 0) + revenue
    max_value = max(order_of_products.values())
    max_keys = [key for key, val in order_of_products.items() if val == max_value]
    return max_keys

In [125]:
top_prods = find_top_product()
print(*top_prods, sep='\n')

Laptop
Mobile

In [127]:
#task 25
def find_top_city():
    top_city = {}
    for order in orders:
        city = order['city']
        top_city[city] = top_city.get(city, 0) + (int(order['quantity']) * int(order['price']))  
        max_value = max(top_city.values())
        max_keys = [k for k,v in top_city.items() if v == max_value]
    return max_keys

In [128]:
top_cities = find_top_city()
print(*top_cities, sep='\n')

Hyderabad

In [94]:
#task 26
def find_average_order_value():
    total_value = 0
    for order in orders:
        total_value += int(order['quantity']) * int(order['price'])
    avg_value_order = total_value / len(orders)
    print(round(avg_value_order, 2))

In [93]:
find_average_order_value()

45666.67

### Part 8 - Exception Handling

In [99]:
#task 27
import csv
orders = []
try:
    with open('C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject1\\orders.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            orders.append(row)
except FileNotFoundError:
    print("make sure the file path is correct and the file exists")

In [100]:
#task 28
def check_quantity():
    try:
        qty = int(order['quantity'])
        if qty<=0:
            raise ValueError('quantity must be positive')
    except ValueError as e:
        print(e)
#we can iterate the data and check for quantity errors

In [101]:
#task 29
def check_price():
    try:
        price = float(orders['price'])
        if price<=0:
            raise ValueError('price cannot be negative')
    except ValueError as e:
       print(e)

### Part 9 - Numpy

In [103]:
#task 30
import numpy as np

order_values = np.array([int(order['quantity']) * int(order['price']) for order in orders])

print(f"total revenue: {np.sum(order_values):,}")
print(f"average revenue: {np.mean(order_values):,.2f}")
print(f"maximum revenue: {np.max(order_values):,}")
print(f"minimum revenue: {np.min(order_values):,}")
print(f"standard deviation: {np.std(order_values):,.2f}")

total revenue: 548,000
average revenue: 45,666.67
maximum revenue: 94,000
minimum revenue: 13,000
standard deviation: 24,560.58

### Part 10 - Pandas

In [105]:
#task 31
import pandas as pd

df = pd.read_csv('C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject1\\orders.csv')
df

    order_id customer_name       city product     category  quantity  price
0       1001  Rahul Sharma  Hyderabad  Laptop  Electronics         1  65000
1       1002   Priya Reddy  Bangalore  Mobile  Electronics         2  25000
2       1003    Amit Kumar     Mumbai   Chair    Furniture         3   5000
3       1004   Sneha Patel    Chennai  Laptop  Electronics         1  70000
4       1005    Farhan Ali      Delhi   Table    Furniture         2  12000
5       1006    Neha Singh  Hyderabad  Mobile  Electronics         1  28000
6       1007   Arjun Verma       Pune   Chair    Furniture         4   5500
7       1008    Meera Nair  Bangalore      TV  Electronics         1  45000
8       1009     Kiran Rao  Hyderabad   Table    Furniture         1  13000
9       1010    Ravi Kumar     Mumbai  Mobile  Electronics         2  27000
10      1011   Deepak Jain      Delhi  Laptop  Electronics         1  68000
11      1012  Ananya Gupta  Hyderabad      TV  Electronics         2  47000

In [106]:
#task 32
df['revenue'] = df['quantity'] * df['price']
df

,order_id,customer_name,city,product,category,quantity,price,revenue
0,1001,Rahul Sharma,Hyderabad,Laptop,Electronics,1,65000,65000
1,1002,Priya Reddy,Bangalore,Mobile,Electronics,2,25000,50000
2,1003,Amit Kumar,Mumbai,Chair,Furniture,3,5000,15000
3,1004,Sneha Patel,Chennai,Laptop,Electronics,1,70000,70000
4,1005,Farhan Ali,Delhi,Table,Furniture,2,12000,24000
5,1006,Neha Singh,Hyderabad,Mobile,Electronics,1,28000,28000
6,1007,Arjun Verma,Pune,Chair,Furniture,4,5500,22000
7,1008,Meera Nair,Bangalore,TV,Electronics,1,45000,45000
8,1009,Kiran Rao,Hyderabad,Table,Furniture,1,13000,13000
9,1010,Ravi Kumar,Mumbai,Mobile,Electronics,2,27000,54000
10,1011,Deepak Jain,Delhi,Laptop,Electronics,1,68000,68000
11,1012,Ananya Gupta,Hyderabad,TV,Electronics,2,47000,94000

In [113]:
#task 33
print("top 5 highest value orders:")
top_five_orders = df.sort_values('revenue', ascending=False).head(5).reset_index(drop=True)
top_five_orders

top 5 highest value orders:

,order_id,customer_name,city,product,category,quantity,price,revenue
0,1012,Ananya Gupta,Hyderabad,TV,Electronics,2,47000,94000
1,1004,Sneha Patel,Chennai,Laptop,Electronics,1,70000,70000
2,1011,Deepak Jain,Delhi,Laptop,Electronics,1,68000,68000
3,1001,Rahul Sharma,Hyderabad,Laptop,Electronics,1,65000,65000
4,1010,Ravi Kumar,Mumbai,Mobile,Electronics,2,27000,54000

In [114]:
#task 34
print("city wise revenue:")
city_revenue_df = df.groupby('city')['revenue'].sum().sort_values(ascending=False).reset_index()
city_revenue_df

city wise revenue:

        city  revenue
0  Hyderabad   200000
1  Bangalore    95000
2      Delhi    92000
3    Chennai    70000
4     Mumbai    69000
5       Pune    22000

In [116]:
#task 35
print("products by revenue")
product_rev_df = df.groupby('product')['revenue'].sum().sort_values(ascending=False).reset_index()
product_rev_df

products by revenue

  product  revenue
0  Laptop   203000
1      TV   139000
2  Mobile   132000
3   Chair    37000
4   Table    37000

In [117]:
#task 36
print("quantity sold by each product")
top_selling_df = df.groupby('product')['quantity'].sum().sort_values(ascending=False).reset_index()
top_selling_df

quantity sold by each product

  product  quantity
0   Chair         7
1  Mobile         5
2  Laptop         3
3      TV         3
4   Table         3

In [119]:
#task 37
print("order in each city")
city_count_df = df.groupby('city')['order_id'].count().sort_values(ascending=False).reset_index()
city_count_df.columns = ['city', 'order count']
city_count_df

order in each city

        city  order count
0  Hyderabad            4
1  Bangalore            2
2     Mumbai            2
3      Delhi            2
4    Chennai            1
5       Pune            1

### Report

In [133]:
top_selling_prods = find_top_product()
top_city = find_top_city()
report_lines = f'''
total orders: {len(orders)}
total revenue: {total_revenue}
average order: {round(avg_value_order,2)}
highest order: {highest_value_order}
lowest order: {lowest_value_order}
revenue by city: {revenue_by_city}
revenue by category: {revenue_by_category}
top selling product: {top_selling_prods}
top revenue city: {top_city}
'''

with open("C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject1\\sales_summary_report.txt","w") as f:
    f.write(report_lines)
print("REPORT GENERATED")

REPORT GENERATED

### Bonus Tasks

In [134]:
high_value_df = df[df['revenue'] > 50000]
high_value_df.to_csv('high_value_orders.csv', index=False)
high_value_df

,order_id,customer_name,city,product,category,quantity,price,revenue
0,1001,Rahul Sharma,Hyderabad,Laptop,Electronics,1,65000,65000
3,1004,Sneha Patel,Chennai,Laptop,Electronics,1,70000,70000
9,1010,Ravi Kumar,Mumbai,Mobile,Electronics,2,27000,54000
10,1011,Deepak Jain,Delhi,Laptop,Electronics,1,68000,68000
11,1012,Ananya Gupta,Hyderabad,TV,Electronics,2,47000,94000

In [135]:
electronics_df = df[df['category'] == 'Electronics']
electronics_df.to_csv('electronics_orders.csv', index=False)
electronics_df

,order_id,customer_name,city,product,category,quantity,price,revenue
0,1001,Rahul Sharma,Hyderabad,Laptop,Electronics,1,65000,65000
1,1002,Priya Reddy,Bangalore,Mobile,Electronics,2,25000,50000
3,1004,Sneha Patel,Chennai,Laptop,Electronics,1,70000,70000
5,1006,Neha Singh,Hyderabad,Mobile,Electronics,1,28000,28000
7,1008,Meera Nair,Bangalore,TV,Electronics,1,45000,45000
9,1010,Ravi Kumar,Mumbai,Mobile,Electronics,2,27000,54000
10,1011,Deepak Jain,Delhi,Laptop,Electronics,1,68000,68000
11,1012,Ananya Gupta,Hyderabad,TV,Electronics,2,47000,94000

In [140]:
def main():
    while True:
        print("1. View Orders")
        print("2. Revenue Analysis")
        print("3. Product Analysis")
        print("4. City Analysis")
        print("5. Export Reports")
        print("6. Exit")

        choice = input("Enter choice (1-6): ")

        if choice == '1':
            
            for o in orders:
                print(o)

        elif choice == '2':
            print(f"total Revenue {total_revenue}")
            print(f"average order value: {avg_value_order}")
            print(f"Highest Order Value: {highest_value_order}")
            print(f"Lowest Order Value: {lowest_value_order}")

        elif choice == '3':
            
            print("Number of orders by each product",order_of_products)
            print("Revenue Generated by each product", revenue_of_products)
            print("Highest Value Sold Product")
            max_sold_value = max(order_of_products.values())
            max_sold_product = [key for key, val in order_of_products.items() if val == max_sold_value]
            print(*max_sold_product, sep='\n')
            print("Lowest Value Sold Product")
            min_sold_value = min(order_of_products.values())
            min_sold_products = [key for key, val in order_of_products.items() if val == min_sold_value]
            print(*min_sold_products, sep='\n')
            revenue_by_category = {}
            print("Revenue By Catergory:")
            for order in orders:
                category = order['category']
                revenue_by_category[category] = revenue_by_category.get(category, 0) + (int(order['quantity']) * int(order['price']))
            print(revenue_by_category)

        elif choice == '4':
            orders_by_city = {}
            for order in orders:
                city = order['city']
            orders_by_city[city] = orders_by_city.get(city, 0) + 1
            print("Orders from each city", orders_by_city)
            #task17 revenue by city
            revenue_by_city = {}
            for order in orders:
                city = order['city']
            revenue_by_city[city] = revenue_by_city.get(city, 0) + (int(order['quantity']) * int(order['price']))  
            print("Revenue Generated by each city", revenue_by_city)
            max_revenue_city_value = max(revenue_by_city.values()) 
            max_revenue_city = [k for k,v in revenue_by_city.items() if v == max_revenue_city_value]
            print(*max_revenue_city, sep='\n')


        elif choice == '5':
            top_selling_prods = find_top_product()
            top_city = find_top_city()
            report_lines = f'''
            total orders: {len(orders)}
            total revenue: {total_revenue}
            average order: {round(avg_value_order,2)}
            highest order: {highest_value_order}
            lowest order: {lowest_value_order}
            revenue by city: {revenue_by_city}
            revenue by category: {revenue_by_category}
            top selling product: {top_selling_prods}
            top revenue city: {top_city}
            '''

            with open("C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\PythonCapstoneProject1\\sales_summary_report.txt","w") as f:
                f.write(report_lines)
            print("REPORT GENERATED")

        elif choice == '6':
            print("Exiting!")
            break
        else:
            print("Invalid choice.")

In [141]:
main()

1. View Orders
2. Revenue Analysis
3. Product Analysis
4. City Analysis
5. Export Reports
6. Exit
{'order_id': '1001', 'customer_name': 'Rahul Sharma', 'city': 'Hyderabad', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '65000'}
{'order_id': '1002', 'customer_name': 'Priya Reddy', 'city': 'Bangalore', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '2', 'price': '25000'}
{'order_id': '1003', 'customer_name': 'Amit Kumar', 'city': 'Mumbai', 'product': 'Chair', 'category': 'Furniture', 'quantity': '3', 'price': '5000'}
{'order_id': '1004', 'customer_name': 'Sneha Patel', 'city': 'Chennai', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '70000'}
{'order_id': '1005', 'customer_name': 'Farhan Ali', 'city': 'Delhi', 'product': 'Table', 'category': 'Furniture', 'quantity': '2', 'price': '12000'}
{'order_id': '1006', 'customer_name': 'Neha Singh', 'city': 'Hyderabad', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '1', 'price': '28000'}
{'order_id': '1007', 'customer_name': 'Arjun Verma', 'city': 'Pune', 'product': 'Chair', 'category': 'Furniture', 'quantity': '4', 'price': '5500'}
{'order_id': '1008', 'customer_name': 'Meera Nair', 'city': 'Bangalore', 'product': 'TV', 'category': 'Electronics', 'quantity': '1', 'price': '45000'}
{'order_id': '1009', 'customer_name': 'Kiran Rao', 'city': 'Hyderabad', 'product': 'Table', 'category': 'Furniture', 'quantity': '1', 'price': '13000'}
{'order_id': '1010', 'customer_name': 'Ravi Kumar', 'city': 'Mumbai', 'product': 'Mobile', 'category': 'Electronics', 'quantity': '2', 'price': '27000'}
{'order_id': '1011', 'customer_name': 'Deepak Jain', 'city': 'Delhi', 'product': 'Laptop', 'category': 'Electronics', 'quantity': '1', 'price': '68000'}
{'order_id': '1012', 'customer_name': 'Ananya Gupta', 'city': 'Hyderabad', 'product': 'TV', 'category': 'Electronics', 'quantity': '2', 'price': '47000'}
1. View Orders
2. Revenue Analysis
3. Product Analysis
4. City Analysis
5. Export Reports
6. Exit
total Revenue 1644000
average order value: 45666.666666666664
Highest Order Value: 94000
Lowest Order Value: 13000
1. View Orders
2. Revenue Analysis
3. Product Analysis
4. City Analysis
5. Export Reports
6. Exit
Exiting!